# Generated by Django 2.0.5 on 2018-05-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20180513_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
