# Generated by Django 2.0.5 on 2018-05-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_auto_20180513_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
